spring:
  application:
    name: appointment-service
  aop:
    proxy-target-class: false
  datasource:
    url: jdbc:mysql://localhost:3307/appointment_service
    username: username
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: none
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expiryAfterAccess=600s
server:
  port: 9090
eureka:
  client:
    service-url:
      defaultZone : http://localhost:8761/eureka/
#resilience4j properties
resilience4j:
  circuitbreaker:
    instances:
      healthProvider:    # Circuit breaker name is "healthProvider" for healthProvider service
        register-health-indicator: true
        sliding-window-type: count_based
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
  retry:
    instances:
      healthProvider: # retry module name is "healthProvider" for healthProvider service
        max-attempts: 3
        wait-duration: 10s

# Actuator properties
management:
  health:
    circuit-breakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org:
      springframework:
        security: DEBUG
app:
  logs:
    fileLocation: C:\Users\isset\SpringBootProjects-Java\microservices-1\microservices-logs # Path to your local machine directory


